print("Descubra a média!")
nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))
media = round((nota1 + nota2) / 2, 1)
print(f"A média entre {nota1} e {nota2} foi de {media}")