frase = input("Digite uma frase: ")
frasePrimitivo = type(frase)
fraseNUm = frase.isalnum()
fraseAlfabet = frase.isalpha()
fraseMaiuscula = frase.isupper()
fraseMinuscula = frase.islower()
fraseEspaco = frase.isspace()
fraseCapitalizado = frase.istitle()
print(f"Tipo primitivo: {frasePrimitivo}")
print(f"É numnérico? {fraseNUm} ")
print(f"É Afabético? {fraseAlfabet} ")
print(f"É Maiúsculo? {fraseMaiuscula} ")
print(f"É minúsculo? {fraseMinuscula} ")
print(f"Está capitalizado? {fraseCapitalizado} ")
print(f"Só tem espaços? {fraseEspaco} ")
