frase = input("Digite uma frase: ")
frase_primitivo = type(frase)
frase_num = frase.isalnum()
frase_alfabet = frase.isalpha()
frase_maiuscula = frase.isupper()
frase_minuscula = frase.islower()
frase_espaco = frase.isspace()
frase_capitalizado = frase.istitle()
print(f"Tipo primitivo: {frase_primitivo}")
print(f"É numnérico? {frase_num} ")
print(f"É Afabético? {frase_alfabet} ")
print(f"É Maiúsculo? {frase_maiuscula} ")
print(f"É minúsculo? {frase_minuscula} ")
print(f"Está capitalizado? {frase_capitalizado} ")
print(f"Só tem espaços? {frase_espaco} ")
